title: Shezad TUFAIL
email: shezad.tufail@gmail.com
description: >- 
  Data Scientist at Essilor based in Singapore.
baseurl: ""
url: ""
twitter_username: shezad_t
github_username:  shezadt

# Build settings
theme: minima
plugins:
  - jekyll-feed
