title: Shezad TUFAIL
email: shezad.tufail@gmail.com
description: >- 
  Last update on April 2020.
baseurl: ""
url: ""
twitter_username: shezad_t
github_username:  shezadt

# Build settings
theme: minima
plugins:
  - jekyll-feed